import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Oluwasusi Stephen Olayemi</title>
      <meta name="description" content=" I design and build beautiful, functional websites that merge creativity with purpose.
              Every project is an opportunity to push boundaries and create something memorable." />
      <meta name="keywords" content="web design, frontend development, UI/UX design, portfolio, creative agency" />
      <meta name="author" content="Oluwasusi Stephen Olayemi" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
